
import { LevelConfig, TileType } from "./types";
import { ArrowUp, ArrowDown, ArrowLeft, ArrowRight, Home, Star, Hexagon } from 'lucide-react';

// Helper to make layout definitions cleaner
const E = TileType.EMPTY;
const W = TileType.WALL;
const S = TileType.START;
const G = TileType.GOAL;
const B = TileType.STAR; // B for Battery/Star

export const LEVELS: LevelConfig[] = [
  // --- TAHAP 1: PENGENALAN (1-5) ---
  {
    id: 1,
    name: "Langkah Pertama",
    description: "Bantu Robo pulang ke rumah!",
    gridSize: 4,
    startPos: { x: 0, y: 0 },
    maxCommands: 5,
    minStarsToWin: 0,
    layout: [
      [S, E, E, E],
      [E, E, E, E],
      [E, E, G, E],
      [E, E, E, E],
    ],
  },
  {
    id: 2,
    name: "Belok Kiri",
    description: "Belajar berbelok itu penting.",
    gridSize: 4,
    startPos: { x: 0, y: 0 },
    maxCommands: 5,
    minStarsToWin: 0,
    layout: [
      [S, E, E, E],
      [E, E, E, E],
      [G, E, E, E],
      [E, E, E, E],
    ],
  },
  {
    id: 3,
    name: "Jalan Lurus",
    description: "Kadang jalan terpendek adalah lurus.",
    gridSize: 4,
    startPos: { x: 0, y: 2 },
    maxCommands: 5,
    minStarsToWin: 0,
    layout: [
      [E, E, E, G],
      [E, E, E, E],
      [S, E, E, E],
      [E, E, E, E],
    ],
  },
  {
    id: 4,
    name: "Zig Zag",
    description: "Gerakan seperti ular!",
    gridSize: 4,
    startPos: { x: 0, y: 0 },
    maxCommands: 8,
    minStarsToWin: 0,
    layout: [
      [S, E, E, E],
      [E, E, E, E],
      [E, E, E, E],
      [E, E, E, G],
    ],
  },
  {
    id: 5,
    name: "Muter-muter",
    description: "Rumahnya ada di belakangmu?",
    gridSize: 3,
    startPos: { x: 0, y: 0 },
    maxCommands: 6,
    minStarsToWin: 0,
    layout: [
      [S, E, E],
      [E, E, E],
      [G, E, E],
    ],
  },

  // --- TAHAP 2: RINTANGAN BATU (6-15) ---
  {
    id: 6,
    name: "Awas Batu!",
    description: "Hindari batu besar itu!",
    gridSize: 4,
    startPos: { x: 0, y: 1 },
    maxCommands: 8,
    minStarsToWin: 0,
    layout: [
      [E, E, E, G],
      [S, W, W, E],
      [E, E, E, E],
      [E, E, E, E],
    ],
  },
  {
    id: 7,
    name: "Lorong Sempit",
    description: "Hati-hati jangan menabrak dinding.",
    gridSize: 4,
    startPos: { x: 0, y: 1 },
    maxCommands: 8,
    minStarsToWin: 0,
    layout: [
      [W, W, W, W],
      [S, E, E, G],
      [W, W, W, W],
      [E, E, E, E],
    ],
  },
  {
    id: 8,
    name: "Labirin Mini",
    description: "Cari jalan keluarnya.",
    gridSize: 4,
    startPos: { x: 0, y: 0 },
    maxCommands: 10,
    minStarsToWin: 0,
    layout: [
      [S, E, W, E],
      [W, E, W, E],
      [E, E, E, E],
      [E, W, W, G],
    ],
  },
  {
    id: 9,
    name: "Huruf U",
    description: "Jalan memutar huruf U.",
    gridSize: 4,
    startPos: { x: 0, y: 0 },
    maxCommands: 10,
    minStarsToWin: 0,
    layout: [
      [S, W, G, E],
      [E, W, E, E],
      [E, E, E, E],
      [W, W, W, W],
    ],
  },
  {
    id: 10,
    name: "Pojok ke Pojok",
    description: "Dari ujung ke ujung.",
    gridSize: 5,
    startPos: { x: 0, y: 0 },
    maxCommands: 12,
    minStarsToWin: 0,
    layout: [
      [S, E, E, W, E],
      [E, W, E, W, E],
      [E, W, E, E, E],
      [E, W, W, W, E],
      [E, E, E, E, G],
    ],
  },
  {
    id: 11,
    name: "Batu Mengapit",
    description: "Lewat tengah-tengah!",
    gridSize: 5,
    startPos: { x: 2, y: 0 },
    maxCommands: 10,
    minStarsToWin: 0,
    layout: [
      [E, E, S, E, E],
      [E, W, E, W, E],
      [E, W, E, W, E],
      [E, W, E, W, E],
      [E, E, G, E, E],
    ],
  },
  {
    id: 12,
    name: "Slalom Robot",
    description: "Kiri kanan kiri kanan.",
    gridSize: 5,
    startPos: { x: 0, y: 2 },
    maxCommands: 12,
    minStarsToWin: 0,
    layout: [
      [E, W, E, W, G],
      [E, W, E, W, E],
      [S, E, E, E, E],
      [W, E, W, E, E],
      [W, E, W, E, E],
    ],
  },
  {
    id: 13,
    name: "Jalan Buntu",
    description: "Jangan tertipu jalan palsu.",
    gridSize: 4,
    startPos: { x: 0, y: 0 },
    maxCommands: 10,
    minStarsToWin: 0,
    layout: [
      [S, E, E, W],
      [W, W, E, W],
      [G, E, E, E],
      [W, W, W, W],
    ],
  },
  {
    id: 14,
    name: "Kotak Kotak",
    description: "Banyak ruangan kecil.",
    gridSize: 4,
    startPos: { x: 0, y: 0 },
    maxCommands: 10,
    minStarsToWin: 0,
    layout: [
      [S, W, E, G],
      [E, W, E, W],
      [E, E, E, W],
      [W, W, E, E],
    ],
  },
  {
    id: 15,
    name: "Tembok Besar",
    description: "Kelilingi tembok raksasa.",
    gridSize: 5,
    startPos: { x: 0, y: 0 },
    maxCommands: 15,
    minStarsToWin: 0,
    layout: [
      [S, E, E, E, E],
      [W, W, W, W, E],
      [E, E, E, W, E],
      [G, W, E, E, E],
      [E, E, E, W, W],
    ],
  },

  // --- TAHAP 3: PEMBURU BINTANG (16-25) ---
  {
    id: 16,
    name: "Bintang Pertama",
    description: "Ambil bintang sebelum pulang!",
    gridSize: 5,
    startPos: { x: 0, y: 0 },
    maxCommands: 10,
    minStarsToWin: 1,
    layout: [
      [S, E, E, E, E],
      [W, W, E, W, E],
      [E, B, E, E, E],
      [E, W, W, W, E],
      [E, E, E, E, G],
    ],
  },
  {
    id: 17,
    name: "Dua Bintang",
    description: "Kumpulkan semua baterai!",
    gridSize: 4,
    startPos: { x: 0, y: 0 },
    maxCommands: 12,
    minStarsToWin: 2,
    layout: [
      [S, E, B, E],
      [E, W, W, E],
      [E, B, W, G],
      [E, E, E, E],
    ],
  },
  {
    id: 18,
    name: "Putar Balik",
    description: "Ambil bintang lalu kembali.",
    gridSize: 4,
    startPos: { x: 0, y: 0 },
    maxCommands: 10,
    minStarsToWin: 1,
    layout: [
      [S, E, E, G],
      [W, W, W, E],
      [B, E, E, E],
      [W, W, W, W],
    ],
  },
  {
    id: 19,
    name: "Pojok Bintang",
    description: "Bintangnya ada di pojok.",
    gridSize: 5,
    startPos: { x: 2, y: 2 },
    maxCommands: 15,
    minStarsToWin: 2,
    layout: [
      [B, E, E, E, B],
      [E, E, E, E, E],
      [E, E, S, E, E],
      [E, E, G, E, E],
      [E, E, E, E, E],
    ],
  },
  {
    id: 20,
    name: "Sik-Asik",
    description: "Ambil bintang sambil menari.",
    gridSize: 5,
    startPos: { x: 0, y: 0 },
    maxCommands: 15,
    minStarsToWin: 2,
    layout: [
      [S, E, W, B, E],
      [E, W, E, W, E],
      [E, B, E, G, E],
      [E, W, E, W, E],
      [E, E, E, E, E],
    ],
  },
  {
    id: 21,
    name: "Serakah",
    description: "Bintangnya banyak sekali!",
    gridSize: 5,
    startPos: { x: 0, y: 2 },
    maxCommands: 20,
    minStarsToWin: 3,
    layout: [
      [E, B, E, B, E],
      [E, E, E, E, E],
      [S, E, B, E, G],
      [E, E, E, E, E],
      [E, B, E, B, E],
    ],
  },
  {
    id: 22,
    name: "Jalan Memutar",
    description: "Jalan pintas ditutup batu.",
    gridSize: 5,
    startPos: { x: 0, y: 0 },
    maxCommands: 15,
    minStarsToWin: 1,
    layout: [
      [S, W, G, E, E],
      [E, W, W, W, E],
      [E, E, E, E, E],
      [W, W, E, W, W],
      [B, E, E, E, E],
    ],
  },
  {
    id: 23,
    name: "Kanan Kiri Oke",
    description: "Pilih jalan terbaik.",
    gridSize: 4,
    startPos: { x: 1, y: 1 },
    maxCommands: 10,
    minStarsToWin: 1,
    layout: [
      [B, E, E, B],
      [E, S, E, E],
      [E, E, G, E],
      [B, E, E, B],
    ],
  },
  {
    id: 24,
    name: "Tersembunyi",
    description: "Bintang sembunyi di balik batu.",
    gridSize: 5,
    startPos: { x: 0, y: 4 },
    maxCommands: 15,
    minStarsToWin: 1,
    layout: [
      [E, E, E, B, W],
      [E, W, W, E, W],
      [E, W, G, E, E],
      [E, W, W, W, E],
      [S, E, E, E, E],
    ],
  },
  {
    id: 25,
    name: "Misi Rahasia",
    description: "Ambil 1 bintang saja cukup.",
    gridSize: 5,
    startPos: { x: 2, y: 2 },
    maxCommands: 10,
    minStarsToWin: 1,
    layout: [
      [B, W, B, W, B],
      [W, E, E, E, W],
      [B, E, S, E, B],
      [W, E, G, E, W],
      [B, W, B, W, B],
    ],
  },

  // --- TAHAP 4: TANTANGAN MASTER (26-33) ---
  {
    id: 26,
    name: "Labirin Kaca",
    description: "Jangan sampai pusing.",
    gridSize: 5,
    startPos: { x: 0, y: 0 },
    maxCommands: 20,
    minStarsToWin: 1,
    layout: [
      [S, E, W, B, E],
      [W, E, W, E, W],
      [E, E, E, E, E],
      [W, E, W, E, W],
      [E, B, W, E, G],
    ],
  },
  {
    id: 27,
    name: "Spiral",
    description: "Berputar seperti obat nyamuk.",
    gridSize: 5,
    startPos: { x: 0, y: 0 },
    maxCommands: 25,
    minStarsToWin: 1,
    layout: [
      [S, E, E, E, E],
      [W, W, W, W, E],
      [E, B, E, W, E],
      [E, W, G, W, E],
      [E, W, W, W, E],
    ],
  },
  {
    id: 28,
    name: "Batu Loncatan",
    description: "Lompat dari satu tempat aman.",
    gridSize: 5,
    startPos: { x: 0, y: 2 },
    maxCommands: 15,
    minStarsToWin: 2,
    layout: [
      [W, B, W, B, W],
      [E, E, E, E, E],
      [S, W, G, W, E],
      [E, E, E, E, E],
      [W, B, W, B, W],
    ],
  },
  {
    id: 29,
    name: "Tiga Sekawan",
    description: "Tiga bintang harus diambil.",
    gridSize: 5,
    startPos: { x: 2, y: 2 },
    maxCommands: 20,
    minStarsToWin: 3,
    layout: [
      [B, E, W, E, B],
      [E, E, E, E, E],
      [W, E, S, E, W],
      [E, E, G, E, E],
      [B, E, W, E, B], // 4 stars available, need 3
    ],
  },
  {
    id: 30,
    name: "Jauh Sekali",
    description: "Perjalanan yang sangat panjang.",
    gridSize: 6,
    startPos: { x: 0, y: 0 },
    maxCommands: 25,
    minStarsToWin: 2,
    layout: [
      [S, E, W, B, E, E],
      [E, E, W, E, W, E],
      [E, W, W, E, W, E],
      [E, E, E, E, E, E],
      [W, W, W, W, W, E],
      [G, E, E, B, E, E],
    ],
  },
  {
    id: 31,
    name: "Gerbang Logika",
    description: "Kunci dulu baru masuk.",
    gridSize: 6,
    startPos: { x: 5, y: 5 },
    maxCommands: 20,
    minStarsToWin: 1,
    layout: [
      [G, W, E, E, E, B],
      [E, W, E, W, W, W],
      [E, W, E, E, E, E],
      [E, E, E, W, W, E],
      [E, W, E, W, E, E],
      [E, E, E, E, E, S],
    ],
  },
  {
    id: 32,
    name: "Simpang Siur",
    description: "Jangan bingung di persimpangan.",
    gridSize: 6,
    startPos: { x: 2, y: 3 },
    maxCommands: 20,
    minStarsToWin: 2,
    layout: [
      [B, E, E, S, E, B],
      [W, W, E, E, E, W],
      [E, E, E, E, E, E],
      [E, W, W, E, W, W],
      [E, E, E, G, E, E],
      [B, E, E, E, E, B],
    ],
  },
  {
    id: 33,
    name: "Istana Robot",
    description: "Tantangan terakhir Raja Robot!",
    gridSize: 6,
    startPos: { x: 0, y: 0 },
    maxCommands: 30,
    minStarsToWin: 3,
    layout: [
      [S, E, E, W, B, E],
      [E, W, E, W, E, W],
      [E, W, B, E, E, E],
      [E, E, E, W, W, E],
      [W, W, E, B, W, G],
      [E, E, E, E, E, E],
    ],
  },
];

export const ICONS = {
  UP: <ArrowUp size={24} strokeWidth={3} />,
  DOWN: <ArrowDown size={24} strokeWidth={3} />,
  LEFT: <ArrowLeft size={24} strokeWidth={3} />,
  RIGHT: <ArrowRight size={24} strokeWidth={3} />,
  HOME: <Home size={28} className="text-white fill-white" />,
  STAR: <Star size={24} className="text-yellow-400 fill-yellow-400 animate-pulse" />,
  WALL: <Hexagon size={28} className="text-gray-600 fill-gray-500" />,
};
